# Generated by Django 5.0.2 on 2024-09-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0003_rename_duração_filme_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='filmes/'),
        ),
    ]
