# Generated by Django 5.0.2 on 2024-09-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0004_filme_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='filme',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
        migrations.AddField(
            model_name='filme',
            name='generos',
            field=models.ManyToManyField(related_name='filmes', to='listApp.genero'),
        ),
    ]
