# Generated by Django 5.0.2 on 2024-09-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0005_genero_alter_filme_imagem_filme_generos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='generos',
            field=models.ManyToManyField(blank=True, to='listApp.genero'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='filmes/'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
