# Generated by Django 5.0.2 on 2024-09-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0007_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
