# Generated by Django 5.0.2 on 2024-09-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0010_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
