# Generated by Django 5.0.2 on 2024-09-22 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0012_usuario_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDeFilmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('filmes', models.ManyToManyField(to='listApp.filme')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listApp.genero')),
            ],
        ),
    ]
