# Generated by Django 5.0.2 on 2024-09-22 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0014_alter_listadefilmes_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadefilmes',
            name='usuario',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='listApp.usuario'),
            preserve_default=False,
        ),
    ]
