# Generated by Django 5.0.2 on 2024-09-22 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0015_listadefilmes_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadefilmes',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listApp.usuario'),
        ),
    ]
