# Generated by Django 5.0.2 on 2024-09-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0016_alter_listadefilmes_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadefilmes',
            name='filmes',
            field=models.ManyToManyField(related_name='list_filmes', to='listApp.filme'),
        ),
    ]
